### ISSUE TITLE
Trigger cross chain status change on reorgs

### ISSUE THREAD

**Issue by monsieurleberre** [stratisproject/FederatedSidechains#135]
***In order to*** make sure transfers previously on chain get to the end destination even after a reorg of the target chain
***As a*** federated member's B-node
***I want*** to trigger a re-validation of the transactions matching the cross chains transfers that were affected by the reorg.

> NOTE:  
    - these transfers can already have been persisted on the new branch onto which the node reorged

#### Acceptance Criteria 

- When a reorg is observed on chain B, the node needs to resync fully, then go through the same resync process as the one that happens upon getting back online (issue XXX)

**Comment by quantumagi** [comment]
The store qualifies its contents by recording both the chain A tip and the chain B tip. As part of the store's rewind process it will revert the status that it maintains for cross-chain-transfer transactions (SeenInBlock -> Fully Signed). This means that the next time we ask the store for transactions ready to be broadcast the reverted transactions will be included.

**Comment by bokobza** [comment]
I think this issue is about what happens when a transaction that is a cross-chain transaction from A to B is part of a block that gets reorged on chain B.

I don't think there is anything for us to do here, as the transaction should go back to the mempool, just like on the normal full node.

@monsieurleberre @quantumagi anything I've missed?
